#!/usr/local/bin/expect -f
set timeout 5
spawn sh
expect "$ "
send "ftp pci\n"
expect "metro): "
send "pci\n"
expect "Password:"
send "admsol\n"
expect "ftp> "
send "bin\n"
expect "ftp> "
send "prompt\n"
expect "ftp> "
send "cd /home/pci/sistema/V\n"
expect "ftp> "
send "mput *.xpm\n"
expect "ftp> "
send "mput *.icons\n"
expect "ftp> "
send "mput *.Raster\n"
expect "ftp> "
send "mput *TextosEstacion*\n"
expect "ftp> "
send "bye\n"
expect "$ "
send "telnet pci\n"
expect "login: "
send "pci\n"
expect "Password: "
send "admsol\n"
expect "$ "
send "pkill plano\n"
expect "$ "
send "exit\n"
expect "$ "
send "exit\n"
